CREATE TABLE countries (
    id VARCHAR(255) PRIMARY KEY
);

INSERT INTO countries (id) VALUES
  ('Bangladesh'),
  ('Indonesia'),
  ('Brunei Darussalam'),
  ('Cameroon'),
  ('Kiribati'),
  ('Sweden'),
  ('Viet Nam'),
  ('Uganda'),
  ('Montenegro'),
  ('Jordan'),
  ('Syrian Arab Republic'),
  ('Dominican Republic'),
  ('Cambodia'),
  ('Papua New Guinea'),
  ('Singapore'),
  ('San Marino'),
  ('Sri Lanka'),
  ('Uzbekistan'),
  ('Colombia'),
  ('United Kingdom of Great Britain and Northern Ireland'),
  ('Albania'),
  ('Grenada'),
  ('Ukraine'),
  ('Saudi Arabia'),
  ('Sao Tome and Principe'),
  ('Cuba'),
  ('Kyrgyzstan'),
  ('Algeria'),
  ('Maldives'),
  ('Djibouti'),
  ('Nauru'),
  ('Senegal'),
  ('Malaysia'),
  ('Ghana'),
  ('Kenya'),
  ('Iceland'),
  ('Zambia'),
  ('Kuwait'),
  ('Madagascar'),
  ('Sierra Leone'),
  ('Liberia'),
  ('Bosnia and Herzegovina'),
  ('Philippines'),
  ('Benin'),
  ('Tuvalu'),
  ('State of Palestine'),
  ('Cabo Verde'),
  ('Guinea'),
  ('Nigeria'),
  ('Liberia''S Updated Ndc'),
  ('Rwanda'),
  ('Tajikistan'),
  ('Zimbabwe'),
  ('Lao People''s Democratic Republic'),
  ('China'),
  ('Comoros'),
  ('Saint Lucia'),
  ('Armenia'),
  ('Belarus'),
  ('Qatar'),
  ('Lesotho'),
  ('Paraguay'),
  ('Gabon'),
  ('Australia'),
  ('Dominica'),
  ('Serbia'),
  ('Angola'),
  ('Bahrain'),
  ('Vanuatu'),
  ('Congo'),
  ('United Arab Emirates'),
  ('Georgia'),
  ('Malawi'),
  ('First Ndc'),
  ('Monaco'),
  ('Burundi'),
  ('Democratic Republic of the Congo'),
  ('Bhutan'),
  ('Republic of Korea'),
  ('Solomon Islands'),
  ('Thailand'),
  ('Togo'),
  ('Niue'),
  ('Burkina Faso'),
  ('El Salvador'),
  ('Democratic People''s Republic of Korea'),
  ('Uruguay'),
  ('Oman'),
  ('Venezuela (Bolivarian Republic of)'),
  ('Micronesia (Federated States of)'),
  ('Fiji'),
  ('Palau'),
  ('Holy See'),
  ('Eritrea'),
  ('Canada'),
  ('Barbados'),
  ('Saint Vincent and the Grenadines'),
  ('United Republic of Tanzania'),
  ('Argentina'),
  ('Namibia'),
  ('Marshall Islands'),
  ('Cook Islands'),
  ('Liechtenstein'),
  ('Azerbaijan'),
  ('Egypt'),
  ('Afghanistan'),
  ('India'),
  ('Chad'),
  ('Timor-Leste'),
  ('Chile'),
  ('Saint Kitts and Nevis'),
  ('Gambia'),
  ('Suriname'),
  ('South Africa'),
  ('Peru'),
  ('Kazakhstan'),
  ('Central African Republic'),
  ('Japan'),
  ('Jamaica'),
  ('Trinidad and Tobago'),
  ('Mongolia'),
  ('United States of America'),
  ('Mauritania'),
  ('Mozambique'),
  ('Seychelles'),
  ('Switzerland'),
  ('New Zealand'),
  ('Ecuador'),
  ('Côte d''Ivoire'),
  ('Honduras'),
  ('Belize'),
  ('Norway'),
  ('Botswana'),
  ('Russian Federation'),
  ('Pakistan'),
  ('Brazil'),
  ('Guatemala'),
  ('Guinea-Bissau'),
  ('Ethiopia'),
  ('Niger'),
  ('Panama'),
  ('South Sudan'),
  ('Turkmenistan'),
  ('Tunisia'),
  ('Sudan'),
  ('Mali'),
  ('North Macedonia'),
  ('Morocco'),
  ('Myanmar'),
  ('Türkiye'),
  ('Nicaragua'),
  ('Mexico'),
  ('Guyana'),
  ('Tonga'),
  ('Nepal'),
  ('Bolivia (Plurinational State of)'),
  ('Lebanon'),
  ('Costa Rica'),
  ('Republic of Moldova'),
  ('Haiti'),
  ('Samoa'),
  ('Equatorial Guinea'),
  ('Antigua and Barbuda'),
  ('Somalia'),
  ('Andorra');