name: Scrape NDC Documents

on:
  # schedule:
  #   - cron: '0 6 * * 1-5'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.11'
          cache: 'pip'

      - name: Install package dependencies
        run: |
          pip install -r requirements/requirements.txt

      - name: Download models
        run: |
          python manual/download_models.py

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Scraper
        run: python "entrypoints/1_scrape.py"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}